--------------------------------------------------------
--  DDL for Table TCDS_JSON_RULES_L01                 --
--------------------------------------------------------
CREATE TABLE DLLCDS.TCDS_JSON_RULES_L01
(
  CDRULE VARCHAR2 (7) DEFAULT ('ND') NOT NULL,
  DSRULE VARCHAR2 (255) DEFAULT ('ND') NOT NULL,
  NMTOPIC NUMBER (10,0) DEFAULT (0) NOT NULL,
  DSJSRULE CLOB DEFAULT ('ND') NOT NULL,
  FECREATED TIMESTAMP NOT NULL,
  DSCREATED_BY VARCHAR2(255) DEFAULT ('ND') NOT NULL,
  FEMODIFIED TIMESTAMP NOT NULL,
  DSMODIFIED_BY VARCHAR2(255) DEFAULT ('ND') NOT NULL,
  NMVOIDED NUMBER(2,0) DEFAULT (1) NOT NULL, 
	FEVOIDED TIMESTAMP NOT NULL,
	DSVOIDED_REASON VARCHAR2(255) NOT NULL
);

COMMENT ON TABLE DLLCDS.TCDS_JSON_RULES_L01 IS 'TABLA PARA ALMACENAR LAS REGLAS EN FORMATO JSON';
COMMENT ON COLUMN DLLCDS.TCDS_JSON_RULES_L01.CDRULE IS 'IDENTIFICADOR DE CADA REGLA FORMADO POR TRES CARACTERES SEGUN EL DIAGNOSTICO Y CUATRO NUMEROS CONSECUTIVOS';
COMMENT ON COLUMN DLLCDS.TCDS_JSON_RULES_L01.DSRULE IS 'DESCRIPCIÓN DE LA REGLA';
COMMENT ON COLUMN DLLCDS.TCDS_JSON_RULES_L01.NMTOPIC IS 'IDENTIFICADOR DEL TOPICO O TEMA AL CUAL PERTENECE LA REGLA';
COMMENT ON COLUMN DLLCDS.TCDS_JSON_RULES_L01.DSJSRULE IS 'OBJETO JSON QUE REPRESENTA LA REGLA';
COMMENT ON COLUMN DLLCDS.TCDS_JSON_RULES_L01.FECREATED IS 'FECHA DE CREACION DEL REGISTRO';
COMMENT ON COLUMN DLLCDS.TCDS_JSON_RULES_L01.DSCREATED_BY IS 'CREADOR DEL REGISTRO';
COMMENT ON COLUMN DLLCDS.TCDS_JSON_RULES_L01.FEMODIFIED IS 'FECHA DE LA MODIFICACION DEL REGISTRO';
COMMENT ON COLUMN DLLCDS.TCDS_JSON_RULES_L01.DSMODIFIED_BY IS 'MODIFICADOR DEL REGISTRO';
COMMENT ON COLUMN DLLCDS.TCDS_JSON_RULES_L01.NMVOIDED IS 'BOOLEANO QUE REPRESENTA EL ESTADO DEL REGISTRO, 1 = ACTIVO, 0 = INACTIVO';
COMMENT ON COLUMN DLLCDS.TCDS_JSON_RULES_L01.FEVOIDED IS 'FECHA DE LA ANULACION DEL REGISTRO';
COMMENT ON COLUMN DLLCDS.TCDS_JSON_RULES_L01.DSVOIDED_REASON IS 'RAZON DE ANULACION DEL REGISTRO';

ALTER TABLE DLLCDS.TCDS_JSON_RULES_L01 MODIFY FECREATED DEFAULT SYSDATE;
ALTER TABLE DLLCDS.TCDS_JSON_RULES_L01 ADD CONSTRAINT TCDS_JSON_RULES_L01_PK PRIMARY KEY (CDRULE);
ALTER TABLE DLLCDS.TCDS_JSON_RULES_L01 ADD CONSTRAINT TCDS_JSON_RULES_L01_FK01 FOREIGN KEY(NMTOPIC) 
	REFERENCES DLLCDS.TCDS_MASTER_ITEMS(NMID);

CREATE OR REPLACE PUBLIC SYNONYM TCDS_JSON_RULES_L01 FOR DLLCDS.TCDS_JSON_RULES_L01;

--------------------------------------------------------
--  SECUENCES for Table TCDS_JSON_RULES_L01           --
--------------------------------------------------------


--------------------------------------------------------
--  DCL for Table TCDS_JSON_RULES_L01          --
--------------------------------------------------------
